project:
    machine_name: timelines
    prefix: TLS
    human_name: 'Timelines'
    profile:
        name: lightning
        contrib: true
    local:
        protocol: http
        hostname: 'local.${project.machine_name}.dd:8083'
git:
    default_branch: master
    remotes:
        - 'mariagwynblt@svn-5599.devcloud.hosting.acquia.com:mariagwynblt.git'
        - 'git@github.com:mariagwyn/mariagwynBLT.git'
drush:
    aliases:
        remote: '${project.machine_name}.test'
        local: self
        ci: self
    default_alias: '${drush.aliases.local}'
target-hooks:
    frontend-setup:
        dir: '${docroot}'
        command: 'echo ''No frontend setup configured.'''
    frontend-build:
        dir: '${docroot}'
        command: 'echo ''No frontend build configured.'''
    post-deploy-build:
        dir: '${deploy.dir}/docroot/profiles/contrib/lightning'
        command: 'npm run install-libraries'
    post-setup-build:
        dir: '${docroot}/profiles/contrib/lightning'
        command: 'npm run install-libraries'
import: null
